---
title: "Homework 4 Problem 2: Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Plotly!

Today I will be using the NYC NOAA dataset.

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(magrittr)
```

```{r}
data("ny_noaa")

ny_noaa %>% 
  slice_sample(n=1000) %>%
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>%
  mutate(tmax = as.numeric(tmax)/10,tmin = as.numeric(tmin)/10)
```

# Creating a Boxplot
```{r}
ny_noaa %>% 
  slice_sample(n=1000) %>%
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>%
  mutate(tmax = as.numeric(tmax)/10,tmin = as.numeric(tmin)/10) %>%
  plot_ly(y = ~tmax, x = ~month, 
          color = ~tmax, type="box", 
          colors="viridis")
```

# Creating a Barplot
```{r}
ny_noaa %>% 
  slice_sample(n=1000) %>%
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>%
  mutate(tmax = as.numeric(tmax)/10,tmin = as.numeric(tmin)/10) %>%
  plot_ly(y = ~snwd, x = ~year, 
          color = ~snwd, type="bar", 
          colors="viridis")
```

# Creating a Scatterplot
```{r}
ny_noaa %>% 
  slice_sample(n=1000) %>%
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>%
  mutate(tmax = as.numeric(tmax)/10,tmin = as.numeric(tmin)/10) %>%
  plot_ly(y = ~tmax, x = ~tmin, 
          color = ~year, type="scatter", 
          colors="viridis")
```